### ISSUE TITLE
New features relating to billing accounts and billing projects

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/django-anvil-consortium-manager#104]
Defining features will take some thought/conversation, but it seems likely that a consortium may need to assign charges to more than one **google** billing project. Practically, this likely means assigning different AnVIL workspaces to different AnVIL billing projects and updating which AnVIL billing project a workspace is associated with.

**Comment by amstilp** [comment]
Closing this issue since we decided not to go this route. That said, I have plans to make the behavior surrounding workspaces more customizable, so that could be covered as a Django project-level customization.
