### ISSUE TITLE
feature request: notification when account is linked

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/django-anvil-consortium-manager#226]
It would be useful if ACM sent a notification to the consortium helpscout email address when a user links their account and can be added to groups.

**Comment by amstilp** [comment]
@wkirdp this might be a good issue for you to work on. I think the steps would be:
* Add a setting `ANVIL_ACCOUNT_VERIFY_NOTIFICATION_EMAIL`
* If `setttings.ANVIL_ACCOUNT_VERIFY_NOTIFICATION_EMAIL` is set, after a user verifies an account with `views.AccountVerify` send an email to the email specified in `settings.ANVIL_ACCOUNT_VERIFY_NOTIFICATION_EMAIL`.
* Add a test to check if the email is sent when `settings.ANVIL_ACCOUNT_VERIFY_NOTIFICATION_EMAIL` is set.
* Add a test to check if the email is *not* sent when `settings.ANVIL_ACCOUNT_VERIFY_NOTIFICATION_EMAIL` is not set.
* Update documentation.
