### ISSUE TITLE
cloning a template doesn't copy analysis notebook

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/django-anvil-consortium-manager#260]
Cloning a workspace is supposed to copy any notebooks in the "analyses" tab to the new workspace. When I used the ACM to clone a template workspace, the resulting workspace did not include the notebook.

**Comment by amstilp** [comment]
This is probably an issue with the AnVIL API. Which workspace are you trying to clone? I can see if it is fixed using the new Rawls API.

**Comment by smgogarten** [comment]
I'm trying to clone PRIMED_template_topmed_data

**Comment by amstilp** [comment]
It looks like you need to pass `"copyFilesWithPrefix": "notebooks"` as part of the JSON body when cloning the workspace. The anvil_api.AnVILAPIClient.clone_workspace method needs to be updated.
