### ISSUE TITLE
feature request: enable search for user accounts

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/django-anvil-consortium-manager#337]
Now that our list of users is getting longer than one page, Sarah C has requested a search feature so that she can look for accounts when offboarding Consortium Members.

**Comment by amstilp** [comment]
@wkirdp In the long run, this is bigger than just searching accounts - we'll need to think about what kind of search features we want overall, for all the models, and then do implement that in a similar way across the app.

Maybe ok to have a temporary search for accounts for now.

**Comment by amstilp** [comment]
Also noting: we should use the Account adapter to help with this search, similar to how the autocomplete view for accounts lets the user define custom autocomplete query filtering.

**Comment by amstilp** [comment]
Talking to Sarah C:
- Searching by the user's name is better, maybe not AnVIL email account. Could also be helpful to search by their consortium email (login). Would like to know "has this person logged into the site"

We decided the best thing to implement would be a user search - one field with an autocomplete field by the name or username for the user, with a button to go to the profile page of that user. This will be implemented in the individual sites and not the app itself.
