### ISSUE TITLE
Design a better UI

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/django-anvil-consortium-manager#49]
Improve the UI design, since right now it is pretty basic and only implemented for quick interactive testing.

Some things to consider in improvements:
- [x] Model string methods
- [x] What to display on templates
- [x] What fields to include in tables
- [ ] Ensure consistency between how different models are displayed
- [x] Choose Icons for buttons, dropdowns, etc.
- [ ] Add more information and instructions where necessary.
- [x] Change "Add" to "Create" in the navbar (to differentiate from "import").
- [x] Make sure buttons are consistent (save, create, add, import)
- [x] Change group detail page to "View groups in this group" and "View accounts in this group". Also mention only direct members
- [x] Show groups and members in alphabetical order
- [x] in WorkspaceGroupAccessForm, Change "can compute" to be more informative - "Allow compute in this workspace"
- [x] Use "share" instead of "access" when giving groups access to a workspace - eg "share a workspace with a group"

**Comment by amstilp** [comment]
Partially addressed in #248

**Comment by smgogarten** [comment]
Typo on the “add group to workspace” page:
A “Reader” can see data int the workspace.
